import { Button, VerticalBox , LineEdit} from "std-widgets.slint";

export component AppWindow inherits Window {
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row{
            Text {
    text: "Enter Total Income";
    horizontal-alignment: center;
    font-size: 24px;
    font-weight: 900;
                }
            }
        Row{
            LineEdit {
                font-size: 16px;
                placeholder-text: "Enter number here";
            }

        }
        Row{
            Button {
                text: "Calculate";
                clicked => { self.text = "Clicked"; }
            }
        }
        
    }
}
